# Generated by Django 5.0.6 on 2024-05-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_director_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='picture',
        ),
    ]
