# Generated by Django 5.0.6 on 2024-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, max_length=40000, null=True, upload_to='movies/'),
        ),
    ]
